name: Frontend

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_UPLOAD_API_SERVER: ${{ secrets.UPLOAD_API_SERVER }}
          file_name: frontend/.env

      - run: npm install
        working-directory: "frontend/"
      
      - run: npm run build
        working-directory: "frontend/"

      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: "frontend/dist"
          container_name: "$web"
          connection_string: ${{ secrets.FRONTEND_CONNECTION_STRING }}
          sync: true
